// This file is auto generated by scripts/build-locales-resource.ts
// Don't modify it manually.

import en from "@/locales/en.json";
import zh_CN from "@/locales/zh_CN.json";

export const resources = {
	en: {
		translation: en,
	},
	zh_CN: {
		translation: zh_CN,
	},
};

export type Resources = (typeof resources)["en"];

export const supportLangs: string[] = ["en", "zh_CN"];
